TAS_SIUKDWStore/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

//untuk keamanan
using System.Security;
using System.Web.Security;
//untuk keamanan

/*untuk identitas pengguna*/
using Microsoft.AspNet.Identity;

using TAS_SIUKDWStore.Models;
using TAS_SIUKDWStore.ViewModels;

namespace TAS_SIUKDWStore.Controllers
{


    //authorisasi hanya untuk pengunjung yang login
    [Authorize]
    public class MessageController : Controller
    {

        private TAS_SIUKDWStoreContext db = new TAS_SIUKDWStoreContext();

        public ActionResult Index()
        {

            var models = from d in db.Messages
                         orderby d.MessageId descending
                         select new MessageViewModel
                         {
                             MessageId = d.MessageId,
                             ContentMessage = d.ContentMessage,
                             UserName = d.UserProfiles.UserName,
                             TimeMessage = d.TimeMessage
                         };
            return View(models);

        }
        //
        // GET: /Buku/Details/5

        public ActionResult Details(int id = 0)
        {

            return View();
        }

        //
        // GET: /Buku/Create

        [Authorize]
        public ActionResult Create()
        {
            var usr = from f in db.UserProfiles
                      where f.UserName == HttpContext.User.Identity.Name
                      select f;

            ViewBag.UserId = new SelectList(usr, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Buku/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Message msg)
        {


            if (ModelState.IsValid)
            {
                db.Messages.Add(msg);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(msg);
        }

        //
        // GET: /Buku/Edit/5
        public ActionResult Edit(int id)
        {
            Message msg = db.Messages.Find(id);
            if (msg == null)
            {
                return HttpNotFound();
            }
         return View(msg);
        }

        //
        // POST: /Buku/Edit/5

        [HttpPost]
        public ActionResult Edit(Message msg)
        {
            if (ModelState.IsValid)
            {
                db.Entry(msg).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(msg);
        }


        //
        // GET: /Buku/Delete/5
        public ActionResult Delete(int? id) 
        {
            var exst = db.Messages.Find(id);



            if (exst !=null)
            {
                Message msg = db.Messages.Find(id);
                db.Messages.Remove(msg);
                db.SaveChanges();
            }
            else
            {

            }
            //if (id == null)
            //{

            //}
            //else if (id <= 0 )
            //{

            //}
            //else if (ModelState.IsValid)
            //{
            //    Message msg = db.Messages.Find(id);
            //    db.Messages.Remove(msg);
            //    db.SaveChanges();


            //}
            return RedirectToAction("Index");
        }

        //
        // POST: /Buku/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Message msg = db.Messages.Find(id);
            db.Messages.Remove(msg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

TAS_SIUKDWStore/Views/Shared/_Bukutamu.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/grid_24.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/style.css">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery-1.7.min.js"></script>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery.easing.1.3.js"></script>
</head>

<body>

    <div class="sub-pages">
        <header>
            <h1><a href="index.html"><img src="@Url.Content("~/Content/mytemplate/")images/logo.png" alt=""></a></h1>
            <nav>
                <ul class="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Buku Tamu", "Index", "Message")</li>
                    <li>@Html.ActionLink("Tulis Buku Tamu", "Create", "Message")</li>
                </ul>
            </nav>
        </header>
    </div>

    <div>
        @RenderBody()
    </div>
</body>
</html>

TAS_SIUKDWStore/Views/Shared/_FluidLayout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

	Nonzero1.0 by nodethirtythree design
	http://www.nodethirtythree.com
	missing in a maze

-->
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
    <title>Guest Book</title>
    <link rel="icon" href="@Url.Content("~/Content/favico.ico")" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    @Styles.Render("~/Content/nonzero/style_blue.css")

</head>
<body>

    <div id="header">
        <div id="header_inner" class="fluid">
            <div id="logo">
                <h1><span>Guest Book</span></h1>
            </div>
            <section style="float: right" id="login">
                @Html.Partial("_LoginPartial")
            </section>
            <div id="menu">

                <ul>
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>              
                    <li>
                        @Html.ActionLink("Messages", "Index", "Message")         
                    </li>
                </ul>

            </div>

        </div>
    </div>

    <div id="main">

        <div id="main_inner" class="fluid">

            <div id="primaryContent_columnless">

                <div id="columnA_columnless">

                    @RenderBody()

                </div>
            </div>
            <div class="post">
                <p>
                    @RenderSection("featured", required: false)
                 </p>
            </div>
                <br class="clear" />
            </div>

        </div>

        <div id="footer" class="fluid">
            Copyright &copy; 2016 Your Website. All rights reserved.
        </div>
        @RenderSection("scripts", required: false)
    </body>
</html>

TAS_SIUKDWStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="@Url.Content("~/Scripts/jquery-ui.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <script type='text/javascript'>
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'fa53c2ae-4348-436e-9c40-c5c15edc73c4'
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Buku Tamu", "Index", "Message")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TAS_SIUKDWStore/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/grid_24.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/style.css">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery-1.7.min.js"></script>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery.easing.1.3.js"></script>
</head>
<body>
    <div class="sub-pages">
        <header>
            <h1><a href="index.html"><img src="@Url.Content("~/Content/mytemplate/")images/logo.png" alt=""></a></h1>
            <nav>
                <ul class="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Buku Tamu", "Index", "Message")</li>
                    <li>@Html.ActionLink("Tulis Buku Tamu", "Create", "Message")</li>
                </ul>
            </nav>
        </header>
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>

TAS_SIUKDWStore/Views/Shared/_mytemplate.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/grid_24.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/style.css">
    <link rel="stylesheet" type="text/css" media="screen" href="@Url.Content("~/Content/mytemplate/")css/slider.css">
    <link href='http://fonts.googleapis.com/css?family=PT+Sans+Narrow:400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery-1.7.min.js"></script>
    <script src="@Url.Content("~/Content/mytemplate/")js/jquery.easing.1.3.js"></script>
    <script src="@Url.Content("~/Content/mytemplate/")js/tms-0.4.1.js"></script>
    <script>
        $(document).ready(function () {
            $('.slider')._TMS({
                show: 0,
                pauseOnHover: true,
                prevBu: '.prev',
                nextBu: '.next',
                playBu: false,
                duration: 800,
                preset: 'fade',
                pagination: '.pags',
                pagNums: false,
                slideshow: 7000,
                numStatus: false,
                banners: false,
                waitBannerAnimation: false,
                progressBar: false
            })
        });
    </script>


    </head>
    <body>
        <header>
            <h1><a href="index.html"><img src="@Url.Content("~/Content/mytemplate/")images/logo.png" alt=""></a></h1>
            <nav>
                <ul class="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Buku Tamu", "Index", "Message")</li>
                    <li>@Html.ActionLink("Tulis Buku Tamu", "Create", "Message")</li>
                        @Html.Partial("_LoginPartial")
                    </ul>

                @*<div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                </div>*@
            
            </nav>
        </header>
        <div id="slide">
            <div class="slider">
                <ul class="items">
                    <li><img src="@Url.Content("~/Content/mytemplate/")images/slide-1.jpg" alt=""></li>
                    <li><img src="@Url.Content("~/Content/mytemplate/")images/slide-2.jpg" alt=""></li>
                    <li><img src="@Url.Content("~/Content/mytemplate/")images/slide-3.jpg" alt=""></li>
                    <li><img src="@Url.Content("~/Content/mytemplate/")images/slide-4.jpg" alt=""></li>
                </ul>
            </div>
            <ul class="pags">
                <li><a href="#"><img src="@Url.Content("~/Content/mytemplate/")images/slide-1-small.jpg" alt=""><span></span></a></li>
                <li><a href="#"><img src="@Url.Content("~/Content/mytemplate/")images/slide-2-small.jpg" alt=""><span></span></a></li>
                <li><a href="#"><img src="@Url.Content("~/Content/mytemplate/")images/slide-3-small.jpg" alt=""><span></span></a></li>
                <li><a href="#"><img src="@Url.Content("~/Content/mytemplate/")mages/slide-4-small.jpg" alt=""><span></span></a></li>
            </ul>
            <a href="#" class="prev">&nbsp;</a><a href="#" class="next">&nbsp;</a>
        </div>


        <div>
            @RenderBody()
        </div>
    </body>
</html>